# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      docker pull grafana/k6
    displayName: Pull k6 image

services:
  k6:
    image: loadimpact/k6:latest
    command: run /tests/k6/tests/stress.js
    volumes:
      - ./tests/k6/tests/stress.js:/tests/k6/tests/stress.js          