version: 0.2

phases:
  pre_build:
    commands:
      - docker build -t helloworld .
  build:
    commands:
      - echo Run performance test
  post_build:
    commands:
      - echo Performance test complete