version: 0.2

phases:
  pre_build:
    commands:
      - echo Pull grafana/k6 image..
      - docker pull grafana/k6
  build:
    commands:
      - echo Run performance test
      - docker run -v $PWD/tests/:/tests -i grafana/k6 run /tests/k6/tests/stress.js
  post_build:
    commands:
      - echo Performance test complete