version: 0.2

phases:
  pre_build:
    commands:
      - echo Pull grafana/k6 image..
      - docker pull grafana/k6
  build:
    commands:
      - echo Run performance test
      - docker run -v ./tests/k6/tests/stress.js:/stress.js -i grafana/k6 run /stress.js
  post_build:
    commands:
      - echo Performance test complete